// <auto-generated />
using System;
using Codprinter.Labels.DataContexts.EFCore.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Codprinter.Labels.DataContexts.EFCore.Migrations
{
    [DbContext(typeof(CodprinterContext))]
    [Migration("20251217205258_AddLabelTables")]
    partial class AddLabelTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Codprinter.Labels.Application.POCOEntities.Assets", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<byte[]>("BinaryData")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("binary_data");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("checksum");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("StorageUrl")
                        .HasColumnType("text")
                        .HasColumnName("storage_url");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Checksum")
                        .IsUnique()
                        .HasDatabaseName("uq_assets_checksum")
                        .HasFilter("checksum IS NOT NULL");

                    b.HasIndex("Type", "Name")
                        .HasDatabaseName("ix_assets_type_name");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("Codprinter.Labels.Application.POCOEntities.DataBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("data_binding_id");

                    b.Property<int?>("CacheTtlSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("cache_ttl_seconds");

                    b.Property<string>("ColumnName")
                        .HasColumnType("text")
                        .HasColumnName("column_name");

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection_name");

                    b.Property<string>("KeyMappingJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_mapping_json");

                    b.Property<Guid>("LabelVariableId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_variable_id");

                    b.Property<string>("QueryType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_type");

                    b.Property<string>("SqlQuery")
                        .HasColumnType("text")
                        .HasColumnName("sql_query");

                    b.Property<string>("TableName")
                        .HasColumnType("text")
                        .HasColumnName("table_name");

                    b.HasKey("Id");

                    b.HasIndex("LabelVariableId")
                        .HasDatabaseName("ix_data_bindings_variable");

                    b.ToTable("data_bindings", (string)null);
                });

            modelBuilder.Entity("Codprinter.Labels.Application.POCOEntities.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LabelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("Codprinter.Labels.Application.POCOEntities.LabelElements", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("label_element_id");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<float?>("HeightMm")
                        .HasColumnType("numeric(9,3)")
                        .HasColumnName("height_mm");

                    b.Property<Guid>("LabelTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_template_id");

                    b.Property<Guid?>("LabelVariableId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_variable_id");

                    b.Property<string>("PropsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("props_json");

                    b.Property<float>("RotationDeg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(6,2)")
                        .HasDefaultValue(0f)
                        .HasColumnName("rotation_deg");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<float?>("WidthMm")
                        .HasColumnType("numeric(9,3)")
                        .HasColumnName("width_mm");

                    b.Property<float>("Xmm")
                        .HasColumnType("numeric(9,3)")
                        .HasColumnName("xmm");

                    b.Property<float>("Ymm")
                        .HasColumnType("numeric(9,3)")
                        .HasColumnName("ymm");

                    b.Property<int>("ZIndex")
                        .HasColumnType("integer")
                        .HasColumnName("z_index");

                    b.HasKey("Id");

                    b.HasIndex("LabelTemplateId", "ZIndex")
                        .HasDatabaseName("ix_label_elements_template_z");

                    b.ToTable("label_elements", (string)null);
                });

            modelBuilder.Entity("Codprinter.Labels.Application.POCOEntities.LabelTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("label_template_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Dpi")
                        .HasColumnType("integer")
                        .HasColumnName("dpi");

                    b.Property<string>("ElementsJson")
                        .HasColumnType("text")
                        .HasColumnName("elements_json");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric(9,3)")
                        .HasColumnName("height_mm");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_json");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("units");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric(9,3)")
                        .HasColumnName("width_mm");

                    b.HasKey("Id");

                    b.HasIndex("TemplateName")
                        .IsUnique()
                        .HasDatabaseName("ix_label_templates_name");

                    b.ToTable("label_templates", (string)null);
                });

            modelBuilder.Entity("Codprinter.Labels.Application.POCOEntities.LabelVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("label_variable_id");

                    b.Property<string>("CalculationExpr")
                        .HasColumnType("text")
                        .HasColumnName("calculation_expr");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_type");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text")
                        .HasColumnName("default_value");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_required");

                    b.Property<Guid>("LabelTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_template_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<string>("ValidationRuleJson")
                        .HasColumnType("text")
                        .HasColumnName("validation_rule_json");

                    b.HasKey("Id");

                    b.HasIndex("LabelTemplateId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_label_variables");

                    b.ToTable("label_variables", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
