// <auto-generated />
using System;
using Codprinter.WeighingScales.DataCOntexts.EFCore.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Codprinter.WeighingScales.DataContext.EFCore.Migrations
{
    [DbContext(typeof(CodprinterContext))]
    [Migration("20251227030957_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Codprinter.WeighingScales.Application.POCOs.WeighingScale", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeighingScaleIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("WeighingScaleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("WeighingScalePort")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WeighingScaleIp")
                        .IsUnique();

                    b.HasIndex("WeighingScaleName")
                        .IsUnique();

                    b.ToTable("WeighingScales", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
