// <auto-generated />
using System;
using CodPrinter.Printers.DataContext.EFCore.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodPrinter.Printers.DataContext.EFCore.Migrations
{
    [DbContext(typeof(CodprinterContext))]
    partial class CodprinterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Codprinter.Printers.Application.POCOs.Printer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("PrinterIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("PrinterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PrinterPort")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PrinterIp")
                        .IsUnique();

                    b.HasIndex("PrinterName")
                        .IsUnique();

                    b.ToTable("Printers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
